# Generated by Django 4.1.1 on 2022-09-10 14:47

import Books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('books_author', models.CharField(max_length=20)),
                ('books_category', models.CharField(max_length=20)),
                ('books_quantity', models.IntegerField()),
            ],
        )
        

    
    ]
